### ISSUE TITLE
Update schema location of DeleteObservation operation?!

### ISSUE THREAD

**Issue by EHJ-52n** [52North/shetland#1]
Shouldn't we point to another source for the schema of the delete observation operation because it will be removed someday?

The link used in the [source code](https://github.com/52North/shetland/blob/master/src/main/java/org/n52/shetland/ogc/sos/delobs/DeleteObservationConstants.java#L56):
```java
    String NS_SOSDO_1_0_SCHEMA_LOCATION =
            "https://raw.githubusercontent.com/52North/SOS/master/extensions/do/xml/src/main/xsd/sosdo.xsd";
```

What about using `http://52north.org/schema/sosdo/1.0|2.0/sosdo.xsd`?

**Comment by autermann** [comment]
How about https://schema.52north.org? We could create a repository on GitHub to collect schema and serve them over that domain. Either by using [GitHub pages](https://help.github.com/articles/setting-up-a-custom-subdomain/) or by hosting it ourselves.

**Comment by autermann** [comment]
Migrated to https://github.com/52North/arctic-sea/issues/3
